title: Sacred Self Ayurveda
description: Discover Balance & Well-Being Through Ayurveda
remote_theme: Bilal2453/cayman-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
