title: Sacred Self Ayurveda
description: Discover Balance & Well-Being Through Ayurveda in the heart of West Michigan
remote_theme: jekyll/minima
Minima:
  skin: auto
plugins:
- jekyll-seo-tag
- jekyll-remote-theme # add this line to the plugins list if you already have one
