title: Sacred Self Ayurveda
description: Discover Balance & Well-Being Through Ayurveda in the heart of West Michigan
#theme: minima
remote_theme: Phlow/feeling-responsive@gh-pages
#remote_theme: jekyll/minima
#Minima:
#  skin: solarized
plugins:
- jekyll-seo-tag
- jekyll-remote-theme # add this line to the plugins list if you already have one
